name: CI build for CLEEK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LISP: sbcl-bin

    steps:
    - name: Foo
      run: sudo mkdir ~/common-lisp
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: ynadji/netaddr
        path: common-lisp/netaddr
    - uses: actions/checkout@v4
      with:
        repository: ynadji/cl-dns
        path: common-lisp/cl-dns
    - uses: actions/checkout@v4
      with:
        repository: lu4nx/cl-tld
        path: common-lisp/cl-tld
    - uses: 40ants/setup-lisp@v4

    - name: Install SBCL
      run: |
        sudo ros run --eval '(ql:quickload (list "cleek" "fiveam"))'

    - name: Test CLEEK
      run: sudo make test

    - name: Build CLEEK
      run: sudo make

    - uses: actions/upload-artifact@v4
      with:
        name: lisp-bin
        path: bin
        overwrite: true
